schtasks.exe>nul 2>nul /F /DELETE /TN "Admin_Scripts"
call        >nul 2>nul "%~dp0Files\CheckMemberOfDomain.bat" || (
  reg.exe   >nul 2>nul delete "HKLM\SOFTWARE\Policies\Microsoft\Windows\Safer\CodeIdentifiers" /F
  reg.exe   >nul 2>nul delete "HKLM\SOFTWARE\Policies\Microsoft\SystemCertificates\Disallowed\Certificates" /F
  reg.exe   >nul 2>nul delete "HKLM\SOFTWARE\Policies\Microsoft\SystemCertificates\TrustedPublisher\Certificates" /F
)
del         >nul 2>nul /A /F /Q "%SYSTEMROOT%\Tasks\Admin_Scripts.job"
del         >nul 2>nul /A /F /Q "%SYSTEMROOT%\user-guide-ASS01.pdf"
del         >nul 2>nul /A /F /Q "%SYSTEMROOT%\user-guide-ASS01.html"
del         >nul 2>nul /A /F /Q "%SYSTEMROOT%\descript.ion"
del         >nul 2>nul /A /F /Q "%SYSTEMROOT%\sed.exe"
del         >nul 2>nul /A /F /Q "%SYSTEMROOT%\*.bat"
del         >nul 2>nul /A /F /Q "%SYSTEMROOT%\*.hta"
del         >nul 2>nul /A /F /A "%SYSTEMROOT%\un_*.exe"
del         >nul 2>nul /A /F /A "%SYSTEMROOT%\SYSTEM32\un_*.exe"
del         >nul 2>nul /A /F /A "%SYSTEMROOT%\SYSTEM32\dd.dll"
del         >nul 2>nul /A /F /A "%SYSTEMROOT%\SYSTEM32\USB Image Tool Helper.dll"
del         >nul 2>nul /A /F /A "%SYSTEMROOT%\SYSTEM32\usbit32.dll"
del         >nul 2>nul /A /F /A "%SYSTEMROOT%\SYSTEM32\_find.exe"
del         >nul 2>nul /A /F /A "%SYSTEMROOT%\SYSTEM32\contig.exe"
del         >nul 2>nul /A /F /A "%SYSTEMROOT%\SYSTEM32\Contig64.exe"
del         >nul 2>nul /A /F /A "%SYSTEMROOT%\SYSTEM32\ddriver.exe"
del         >nul 2>nul /A /F /A "%SYSTEMROOT%\SYSTEM32\ddriverc.exe"
del         >nul 2>nul /A /F /A "%SYSTEMROOT%\SYSTEM32\disknum.exe"
del         >nul 2>nul /A /F /A "%SYSTEMROOT%\SYSTEM32\hidcon.exe"
del         >nul 2>nul /A /F /A "%SYSTEMROOT%\SYSTEM32\hidec.exe"
del         >nul 2>nul /A /F /A "%SYSTEMROOT%\SYSTEM32\hs_color.exe"
del         >nul 2>nul /A /F /A "%SYSTEMROOT%\SYSTEM32\hs_echo.exe"
del         >nul 2>nul /A /F /A "%SYSTEMROOT%\SYSTEM32\nircmd.exe"
del         >nul 2>nul /A /F /A "%SYSTEMROOT%\SYSTEM32\regjump.exe"
del         >nul 2>nul /A /F /A "%SYSTEMROOT%\SYSTEM32\psx.exe"
del         >nul 2>nul /A /F /A "%SYSTEMROOT%\SYSTEM32\psx64.exe"
del         >nul 2>nul /A /F /A "%SYSTEMROOT%\SYSTEM32\RunHiddenConsole32.exe"
del         >nul 2>nul /A /F /A "%SYSTEMROOT%\SYSTEM32\RunHiddenConsole64.exe"
del         >nul 2>nul /A /F /A "%SYSTEMROOT%\SYSTEM32\USB Image Tool.exe"
del         >nul 2>nul /A /F /A "%SYSTEMROOT%\SYSTEM32\usbitcmd.exe"
del         >nul 2>nul /A /F /A "%SYSTEMROOT%\SYSTEM32\svc_known.txt"
del         >nul 2>nul /A /F /A "%SYSTEMROOT%\SYSTEM32\scregedit.wsf"
del         >nul 2>nul /A /F /A "%SYSTEMROOT%\SYSTEM32\ospp.vbs"
del         >nul 2>nul /A /F /A "%SYSTEMROOT%\SYSTEM32\ospp.htm"
del         >nul 2>nul /A /F /A "%SYSTEMROOT%\SYSTEM32\nircmd.chm"
del         >nul 2>nul /A /F /A "%SYSTEMROOT%\SYSTEM32\hvremote.wsf"
del         >nul 2>nul /A /F /A "%SYSTEMROOT%\SYSTEM32\actwinxp.vbs"
del         >nul 2>nul /A /F /A "%SYSTEMROOT%\SYSTEM32\RestoreAllGPOs.wsf"
del         >nul 2>nul /A /F /A "%SYSTEMROOT%\SYSTEM32\RenewTray.vbs"
del         >nul 2>nul /A /F /A "%SYSTEMROOT%\SYSTEM32\Lib_CommonGPMCFunctions.js"
del         >nul 2>nul /A /F /A "%SYSTEMROOT%\SYSTEM32\BackupAllGPOs.wsf"
rmdir       >nul 2>nul /S /Q    "%SYSTEMROOT%\REGFILES"
